# Generated by Django 5.0.1 on 2024-01-22 16:23

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_image',
            field=models.ImageField(blank=True, null=True, upload_to='categories_img/', verbose_name='Category image'),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='category',
            name='deleted_at',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='Deleted at'),
        ),
        migrations.AlterField(
            model_name='category',
            name='restored_at',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='Restored at'),
        ),
        migrations.AlterField(
            model_name='category',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='products.category', verbose_name='Sub Categories'),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='images',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='images',
            name='deleted_at',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='Deleted at'),
        ),
        migrations.AlterField(
            model_name='images',
            name='restored_at',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='Restored at'),
        ),
        migrations.AlterField(
            model_name='images',
            name='updated_at',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='product',
            name='deleted_at',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='Deleted at'),
        ),
        migrations.AlterField(
            model_name='product',
            name='restored_at',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='Restored at'),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='product_img/', verbose_name='Product thumbnail'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
    ]
